-- ============================================================
-- CARPEDIEM TECH — GRANTS + SEED DATA
-- Run this once in the Supabase SQL Editor (Dashboard → SQL Editor).
-- It restores the table privileges every role was missing, then
-- inserts 5 mentors and 20 current-trend courses.
-- Safe to re-run (idempotent).
-- ============================================================

-- 1) Restore privileges (this is why the site showed 401/permission denied)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT SELECT ON public.courses, public.mentors, public.testimonials, public.settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.courses, public.mentors, public.testimonials, public.settings TO authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated, service_role;

-- 2) Ensure realtime is enabled for settings too
DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.settings; EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- 3) Seed mentors (idempotent by name)
DELETE FROM public.mentors WHERE name IN ('Arun Kumar', 'Dr. Priya Ramakrishnan', 'Suresh Murugesan', 'Magesh Sundar', 'Karthik Rajan');
INSERT INTO public.mentors (name, designation, company, experience, bio, linkedin, github, twitter, website, skills, profile_image, display_order, featured_toggle, status) VALUES
  ('Arun Kumar', 'Full-Stack Architect', 'Ex-Amazon', '10+ years', 'Ex-SDE at Amazon. Builds high-scale distributed commerce systems and mentors engineers on clean architecture.', 'https://linkedin.com/in/arunkumar', 'https://github.com/arunkumar', NULL, NULL, ARRAY['React', 'Node.js', 'System Design', 'AWS', 'TypeScript']::text[], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80', 1, true, 'active'),
  ('Dr. Priya Ramakrishnan', 'Generative AI Lead', 'PhD, ML', '12+ years', 'Ph.D. in Machine Learning. Consults on enterprise RAG pipelines, LLM fine-tuning and autonomous agent deployments.', 'https://linkedin.com/in/priyaramakrishnan', NULL, NULL, NULL, ARRAY['LLMs', 'PyTorch', 'RAG', 'Prompt Engineering', 'Python']::text[], 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80', 2, true, 'active'),
  ('Suresh Murugesan', 'Cloud & DevOps Specialist', 'AWS Certified', '9+ years', 'AWS Solutions Lead. Managed large-scale Kubernetes clusters and CI/CD platforms for fintech and SaaS teams.', 'https://linkedin.com/in/sureshmurugesan', NULL, NULL, NULL, ARRAY['Kubernetes', 'AWS', 'Terraform', 'Docker', 'CI/CD']::text[], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80', 3, true, 'active'),
  ('Magesh Sundar', 'Senior Product Designer', 'Ex-Cognizant', '8+ years', 'Former Senior UX Designer. Shipped consumer products used by millions and leads design systems practice.', 'https://linkedin.com/in/mageshsundar', NULL, NULL, NULL, ARRAY['Figma', 'UX Research', 'Design Systems', 'Prototyping']::text[], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80', 4, true, 'active'),
  ('Karthik Rajan', 'Cybersecurity & Data Lead', 'OSCP Certified', '11+ years', 'Offensive security expert and data engineer. Runs red-team engagements and builds streaming data platforms.', 'https://linkedin.com/in/karthikrajan', NULL, NULL, NULL, ARRAY['Ethical Hacking', 'Python', 'Spark', 'SIEM', 'Networking']::text[], 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80', 5, false, 'active');

-- 4) Seed courses (idempotent by slug)
INSERT INTO public.courses (title, slug, category, description, long_description, overview, difficulty, duration, language, instructor, price, discount_price, course_image, rating, students_enrolled, certificate_included, projects_included, placement_support, tools_covered, career_outcomes, requirements, status, seo_title, seo_description, meta_keywords, is_published) VALUES
  ('Full-Stack Development with React & Node.js', 'full-stack-development-with-react-node-js', 'Software Engineering', 'Build production-grade full-stack apps with React, Node.js, and PostgreSQL.', 'Build production-grade full-stack apps with React, Node.js, and PostgreSQL. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 6 production-grade projects.', 'Build production-grade full-stack apps with React, Node.js, and PostgreSQL.', 'Beginner', '16 Weeks', 'English', 'Arun Kumar', '₹22,000', '₹34,000', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80', 4.9, 1240, true, 6, true, ARRAY['React', 'Node.js', 'Express', 'PostgreSQL', 'TypeScript', 'Docker']::text[], ARRAY['Full-Stack Developer', 'Backend Engineer', 'SDE-1']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Full-Stack Development with React & Node.js | Carpediem Tech', 'Build production-grade full-stack apps with React, Node.js, and PostgreSQL.', 'React, Node.js, Express, PostgreSQL, TypeScript, Docker', true),
  ('Generative AI & LLM Application Development', 'generative-ai-llm-application-development', 'Artificial Intelligence', 'Ship real GenAI products with LLMs, RAG pipelines, and vector databases.', 'Ship real GenAI products with LLMs, RAG pipelines, and vector databases. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Ship real GenAI products with LLMs, RAG pipelines, and vector databases.', 'Intermediate', '12 Weeks', 'English', 'Dr. Priya Ramakrishnan', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80', 4.9, 980, true, 5, true, ARRAY['OpenAI', 'LangChain', 'RAG', 'Pinecone', 'Python']::text[], ARRAY['AI Engineer', 'LLM Developer', 'ML Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Generative AI & LLM Application Development | Carpediem Tech', 'Ship real GenAI products with LLMs, RAG pipelines, and vector databases.', 'OpenAI, LangChain, RAG, Pinecone, Python', true),
  ('Prompt Engineering & AI Agents', 'prompt-engineering-ai-agents', 'Artificial Intelligence', 'Design reliable prompts and build multi-agent automations with modern frameworks.', 'Design reliable prompts and build multi-agent automations with modern frameworks. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 4 production-grade projects.', 'Design reliable prompts and build multi-agent automations with modern frameworks.', 'Beginner', '8 Weeks', 'English', 'Dr. Priya Ramakrishnan', '₹22,000', '₹34,000', 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?auto=format&fit=crop&w=800&q=80', 4.8, 1520, true, 4, true, ARRAY['Prompt Engineering', 'LangGraph', 'n8n', 'Agents', 'Python']::text[], ARRAY['AI Automation Engineer', 'Prompt Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Prompt Engineering & AI Agents | Carpediem Tech', 'Design reliable prompts and build multi-agent automations with modern frameworks.', 'Prompt Engineering, LangGraph, n8n, Agents, Python', true),
  ('Cloud Architecture with AWS', 'cloud-architecture-with-aws', 'Cloud & DevOps', 'Design scalable, cost-efficient cloud systems and prepare for AWS certification.', 'Design scalable, cost-efficient cloud systems and prepare for AWS certification. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 6 production-grade projects.', 'Design scalable, cost-efficient cloud systems and prepare for AWS certification.', 'Intermediate', '14 Weeks', 'English', 'Suresh Murugesan', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', 4.8, 860, true, 6, true, ARRAY['AWS', 'EC2', 'S3', 'Lambda', 'CloudFormation']::text[], ARRAY['Cloud Engineer', 'Solutions Architect']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Cloud Architecture with AWS | Carpediem Tech', 'Design scalable, cost-efficient cloud systems and prepare for AWS certification.', 'AWS, EC2, S3, Lambda, CloudFormation', true),
  ('Kubernetes & DevOps Engineering', 'kubernetes-devops-engineering', 'Cloud & DevOps', 'Master containers, Kubernetes, GitOps, and production-grade CI/CD pipelines.', 'Master containers, Kubernetes, GitOps, and production-grade CI/CD pipelines. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Master containers, Kubernetes, GitOps, and production-grade CI/CD pipelines.', 'Advanced', '12 Weeks', 'English', 'Suresh Murugesan', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80', 4.7, 720, true, 5, true, ARRAY['Kubernetes', 'Docker', 'Helm', 'ArgoCD', 'GitHub Actions']::text[], ARRAY['DevOps Engineer', 'Platform Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Kubernetes & DevOps Engineering | Carpediem Tech', 'Master containers, Kubernetes, GitOps, and production-grade CI/CD pipelines.', 'Kubernetes, Docker, Helm, ArgoCD, GitHub Actions', true),
  ('Data Engineering with Python & Spark', 'data-engineering-with-python-spark', 'Artificial Intelligence', 'Build batch and streaming data pipelines at scale with Spark and Airflow.', 'Build batch and streaming data pipelines at scale with Spark and Airflow. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Build batch and streaming data pipelines at scale with Spark and Airflow.', 'Intermediate', '14 Weeks', 'English', 'Karthik Rajan', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', 4.7, 640, true, 5, true, ARRAY['Python', 'Apache Spark', 'Airflow', 'Kafka', 'SQL']::text[], ARRAY['Data Engineer', 'Analytics Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Data Engineering with Python & Spark | Carpediem Tech', 'Build batch and streaming data pipelines at scale with Spark and Airflow.', 'Python, Apache Spark, Airflow, Kafka, SQL', true),
  ('Machine Learning & MLOps', 'machine-learning-mlops', 'Artificial Intelligence', 'From model training to deployment — the full ML lifecycle with MLOps best practices.', 'From model training to deployment — the full ML lifecycle with MLOps best practices. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 6 production-grade projects.', 'From model training to deployment — the full ML lifecycle with MLOps best practices.', 'Advanced', '16 Weeks', 'English', 'Dr. Priya Ramakrishnan', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80', 4.8, 590, true, 6, true, ARRAY['scikit-learn', 'MLflow', 'Docker', 'FastAPI', 'Python']::text[], ARRAY['ML Engineer', 'MLOps Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Machine Learning & MLOps | Carpediem Tech', 'From model training to deployment — the full ML lifecycle with MLOps best practices.', 'scikit-learn, MLflow, Docker, FastAPI, Python', true),
  ('Cybersecurity & Ethical Hacking', 'cybersecurity-ethical-hacking', 'Cloud & DevOps', 'Hands-on offensive security: pentesting, exploitation, and defense.', 'Hands-on offensive security: pentesting, exploitation, and defense. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Hands-on offensive security: pentesting, exploitation, and defense.', 'Intermediate', '14 Weeks', 'English', 'Karthik Rajan', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=800&q=80', 4.9, 810, true, 5, true, ARRAY['Kali Linux', 'Burp Suite', 'Metasploit', 'Networking', 'OSCP']::text[], ARRAY['Security Analyst', 'Penetration Tester']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Cybersecurity & Ethical Hacking | Carpediem Tech', 'Hands-on offensive security: pentesting, exploitation, and defense.', 'Kali Linux, Burp Suite, Metasploit, Networking, OSCP', true),
  ('UI/UX Product Design', 'ui-ux-product-design', 'Product Design', 'Design delightful, accessible product experiences from research to high-fidelity UI.', 'Design delightful, accessible product experiences from research to high-fidelity UI. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 4 production-grade projects.', 'Design delightful, accessible product experiences from research to high-fidelity UI.', 'Beginner', '10 Weeks', 'English', 'Magesh Sundar', '₹22,000', '₹34,000', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80', 4.8, 1100, true, 4, true, ARRAY['Figma', 'User Research', 'Wireframing', 'Design Systems']::text[], ARRAY['Product Designer', 'UX Designer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'UI/UX Product Design | Carpediem Tech', 'Design delightful, accessible product experiences from research to high-fidelity UI.', 'Figma, User Research, Wireframing, Design Systems', true),
  ('Mobile App Development with Flutter', 'mobile-app-development-with-flutter', 'Software Engineering', 'Build cross-platform iOS & Android apps from one Flutter codebase.', 'Build cross-platform iOS & Android apps from one Flutter codebase. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Build cross-platform iOS & Android apps from one Flutter codebase.', 'Intermediate', '12 Weeks', 'English', 'Arun Kumar', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80', 4.7, 690, true, 5, true, ARRAY['Flutter', 'Dart', 'Firebase', 'REST APIs']::text[], ARRAY['Mobile Developer', 'Flutter Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Mobile App Development with Flutter | Carpediem Tech', 'Build cross-platform iOS & Android apps from one Flutter codebase.', 'Flutter, Dart, Firebase, REST APIs', true),
  ('Next.js 15 & Modern Web Engineering', 'next-js-15-modern-web-engineering', 'Software Engineering', 'Server components, edge rendering, and full-stack Next.js for production.', 'Server components, edge rendering, and full-stack Next.js for production. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Server components, edge rendering, and full-stack Next.js for production.', 'Intermediate', '10 Weeks', 'English', 'Arun Kumar', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80', 4.8, 940, true, 5, true, ARRAY['Next.js', 'React', 'TypeScript', 'Tailwind', 'Vercel']::text[], ARRAY['Frontend Engineer', 'Full-Stack Developer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Next.js 15 & Modern Web Engineering | Carpediem Tech', 'Server components, edge rendering, and full-stack Next.js for production.', 'Next.js, React, TypeScript, Tailwind, Vercel', true),
  ('Python for Data Science', 'python-for-data-science', 'Artificial Intelligence', 'Analyze, visualize, and model data with the modern Python data stack.', 'Analyze, visualize, and model data with the modern Python data stack. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 4 production-grade projects.', 'Analyze, visualize, and model data with the modern Python data stack.', 'Beginner', '10 Weeks', 'English', 'Karthik Rajan', '₹22,000', '₹34,000', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80', 4.7, 1680, true, 4, true, ARRAY['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Jupyter']::text[], ARRAY['Data Analyst', 'Data Scientist']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Python for Data Science | Carpediem Tech', 'Analyze, visualize, and model data with the modern Python data stack.', 'Python, Pandas, NumPy, Matplotlib, Jupyter', true),
  ('Blockchain & Web3 Development', 'blockchain-web3-development', 'Software Engineering', 'Write smart contracts and build decentralized apps on EVM chains.', 'Write smart contracts and build decentralized apps on EVM chains. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Write smart contracts and build decentralized apps on EVM chains.', 'Advanced', '12 Weeks', 'English', 'Arun Kumar', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?auto=format&fit=crop&w=800&q=80', 4.6, 420, true, 5, true, ARRAY['Solidity', 'Ethereum', 'Hardhat', 'Web3.js', 'IPFS']::text[], ARRAY['Blockchain Developer', 'Smart Contract Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Blockchain & Web3 Development | Carpediem Tech', 'Write smart contracts and build decentralized apps on EVM chains.', 'Solidity, Ethereum, Hardhat, Web3.js, IPFS', true),
  ('DevSecOps & CI/CD Automation', 'devsecops-ci-cd-automation', 'Cloud & DevOps', 'Bake security into pipelines with automated scanning and policy-as-code.', 'Bake security into pipelines with automated scanning and policy-as-code. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Bake security into pipelines with automated scanning and policy-as-code.', 'Advanced', '10 Weeks', 'English', 'Suresh Murugesan', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80', 4.7, 380, true, 5, true, ARRAY['GitHub Actions', 'SonarQube', 'Trivy', 'Terraform', 'OPA']::text[], ARRAY['DevSecOps Engineer', 'SRE']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'DevSecOps & CI/CD Automation | Carpediem Tech', 'Bake security into pipelines with automated scanning and policy-as-code.', 'GitHub Actions, SonarQube, Trivy, Terraform, OPA', true),
  ('Deep Learning with PyTorch', 'deep-learning-with-pytorch', 'Artificial Intelligence', 'Build and train neural networks for vision and NLP with PyTorch.', 'Build and train neural networks for vision and NLP with PyTorch. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 6 production-grade projects.', 'Build and train neural networks for vision and NLP with PyTorch.', 'Advanced', '14 Weeks', 'English', 'Dr. Priya Ramakrishnan', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80', 4.8, 560, true, 6, true, ARRAY['PyTorch', 'CNNs', 'Transformers', 'CUDA', 'Python']::text[], ARRAY['Deep Learning Engineer', 'AI Researcher']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Deep Learning with PyTorch | Carpediem Tech', 'Build and train neural networks for vision and NLP with PyTorch.', 'PyTorch, CNNs, Transformers, CUDA, Python', true),
  ('Product Management Essentials', 'product-management-essentials', 'Product Design', 'Discovery, roadmaps, metrics, and stakeholder work to ship products that matter.', 'Discovery, roadmaps, metrics, and stakeholder work to ship products that matter. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 3 production-grade projects.', 'Discovery, roadmaps, metrics, and stakeholder work to ship products that matter.', 'Beginner', '8 Weeks', 'English', 'Magesh Sundar', '₹22,000', '₹34,000', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', 4.6, 730, true, 3, true, ARRAY['Roadmapping', 'User Stories', 'Analytics', 'A/B Testing']::text[], ARRAY['Associate Product Manager', 'Product Owner']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Product Management Essentials | Carpediem Tech', 'Discovery, roadmaps, metrics, and stakeholder work to ship products that matter.', 'Roadmapping, User Stories, Analytics, A/B Testing', true),
  ('Rust Systems Programming', 'rust-systems-programming', 'Software Engineering', 'Write fast, memory-safe systems software with Rust.', 'Write fast, memory-safe systems software with Rust. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Write fast, memory-safe systems software with Rust.', 'Advanced', '12 Weeks', 'English', 'Arun Kumar', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80', 4.7, 310, true, 5, true, ARRAY['Rust', 'Cargo', 'Tokio', 'WebAssembly']::text[], ARRAY['Systems Engineer', 'Backend Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Rust Systems Programming | Carpediem Tech', 'Write fast, memory-safe systems software with Rust.', 'Rust, Cargo, Tokio, WebAssembly', true),
  ('Golang Backend Engineering', 'golang-backend-engineering', 'Software Engineering', 'Build high-performance microservices and APIs with Go.', 'Build high-performance microservices and APIs with Go. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Build high-performance microservices and APIs with Go.', 'Intermediate', '12 Weeks', 'English', 'Suresh Murugesan', '₹28,000', '₹42,000', 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=800&q=80', 4.7, 500, true, 5, true, ARRAY['Go', 'gRPC', 'PostgreSQL', 'Docker', 'Microservices']::text[], ARRAY['Backend Engineer', 'Golang Developer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Golang Backend Engineering | Carpediem Tech', 'Build high-performance microservices and APIs with Go.', 'Go, gRPC, PostgreSQL, Docker, Microservices', true),
  ('Computer Vision & Image AI', 'computer-vision-image-ai', 'Artificial Intelligence', 'Detection, segmentation, and generative image models in production.', 'Detection, segmentation, and generative image models in production. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Detection, segmentation, and generative image models in production.', 'Advanced', '12 Weeks', 'English', 'Dr. Priya Ramakrishnan', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80', 4.7, 440, true, 5, true, ARRAY['OpenCV', 'YOLO', 'PyTorch', 'Diffusion Models']::text[], ARRAY['Computer Vision Engineer', 'AI Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Computer Vision & Image AI | Carpediem Tech', 'Detection, segmentation, and generative image models in production.', 'OpenCV, YOLO, PyTorch, Diffusion Models', true),
  ('Site Reliability Engineering (SRE)', 'site-reliability-engineering-sre', 'Cloud & DevOps', 'Observability, SLOs, incident response, and resilient systems at scale.', 'Observability, SLOs, incident response, and resilient systems at scale. This project-based program includes weekly mentorship, code reviews, real deployments, and placement support. You''ll graduate with a portfolio of 5 production-grade projects.', 'Observability, SLOs, incident response, and resilient systems at scale.', 'Advanced', '12 Weeks', 'English', 'Suresh Murugesan', '₹34,000', '₹52,000', 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80', 4.8, 360, true, 5, true, ARRAY['Prometheus', 'Grafana', 'Kubernetes', 'Terraform', 'PagerDuty']::text[], ARRAY['SRE', 'Platform Engineer']::text[], ARRAY['Laptop with 8GB+ RAM', 'Stable internet', '3–4 hours daily commitment']::text[], 'published', 'Site Reliability Engineering (SRE) | Carpediem Tech', 'Observability, SLOs, incident response, and resilient systems at scale.', 'Prometheus, Grafana, Kubernetes, Terraform, PagerDuty', true)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  overview = EXCLUDED.overview,
  difficulty = EXCLUDED.difficulty,
  duration = EXCLUDED.duration,
  language = EXCLUDED.language,
  instructor = EXCLUDED.instructor,
  price = EXCLUDED.price,
  discount_price = EXCLUDED.discount_price,
  course_image = EXCLUDED.course_image,
  rating = EXCLUDED.rating,
  students_enrolled = EXCLUDED.students_enrolled,
  certificate_included = EXCLUDED.certificate_included,
  projects_included = EXCLUDED.projects_included,
  placement_support = EXCLUDED.placement_support,
  tools_covered = EXCLUDED.tools_covered,
  career_outcomes = EXCLUDED.career_outcomes,
  requirements = EXCLUDED.requirements,
  status = EXCLUDED.status,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  meta_keywords = EXCLUDED.meta_keywords,
  is_published = EXCLUDED.is_published;
